### PR TITLE
Update embxx to most current version

### PR DESCRIPTION
**Pull request by simonCor**
This fixes the problem described in https://github.com/arobenko/embxx_on_rpi/issues/10

### CODE REVIEW

**Review by arobenko — CHANGES_REQUESTED** [review]
Good job. All the fixes look perfect.
However it looks like you submitted pull request with changes to embxx on embxx_on_rpi project.
Could you please submit the changes to the embxx project doing the following:

- checkout the "hotfixes" branch.
- merge "master" to "hotfixes" (should be simple fast-forward).
- apply your changes to "hotfixes" branch and submit the pull-request on it.

I'll merge your pull-request and then merge "hotfixes" to master myself doing the next official release.
Thanks.

**Comment by simonCor** [comment]
Hm I do not use github very often - maybe I am mistaken.

The only thing I did was to update the version of the submodule embxx on the embxx_on_rpi project. So IMHO this is a change to embxx_on_rpi project not embxx.

**Comment by arobenko** [comment]
That's right [embxx](https://github.com/arobenko/embxx/) project is a git submodule of [embxx_on_rpi](https://github.com/arobenko/embxx_on_rpi/). The proper way to fix the build of the latter is to introduce changes to the former first, and then update the right revision of the submodule to checkout.

**Comment by simonCor** [comment]
Yes but there are no changes to embxx. The issue is that the submodule in embxx_on_rpi refers to an old commit (29d1fa4de0dd7fb520dd4282b5cea6e38f024e09 which is release 0.11) on master of embxx.

I just updated this to commit 2dcf10725cd6dd6d587e7c06397b3514c2cb42be which is release 0.12.3.

So in my opinion this change is purely on embxx_on_rpi.

**Comment by arobenko** [comment]
Sorry, my mistake. 
The way how your pull request was displayed, confused me. It looked like you introduce multiple changes to embxx library. I haven't touched the latter for a while and didn't realized that the changes I saw were already implemented.

There was some small pending fix in WriteQueue class that I just slipped in, and as the result the latest version of embxx is v0.12.4. I modified this project myself to point to this latest release.

Anyway, thanks for drawing my attention to the fact that this project used outdated embxx.

**Pull request closed without merging**
